# Generated by Django 5.0.1 on 2024-03-10 12:16

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', django_jalali.db.models.jDateField(auto_created=True, blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(editable=False)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('job_time', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('token', models.CharField(default=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL), max_length=1000)),
                ('last_info', models.TextField(blank=True, default=' +', max_length=1000, null=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_AttendanceUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
