# Generated by Django 5.0.1 on 2024-03-14 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='confirmation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='last_info',
            field=models.TextField(blank=True, default=' +', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='token',
            field=models.CharField(default=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
