# Generated by Django 5.0.1 on 2024-03-02 14:38

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0002_alter_attendanceuser_token_alter_attendanceuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_date',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2024, 3, 2), null=True),
        ),
    ]
