# Generated by Django 4.2 on 2024-03-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0002_attendanceuser_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='confirmation',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
