# Generated by Django 5.0.1 on 2024-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0003_alter_attendanceuser_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='month',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
