# Generated by Django 4.2 on 2024-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0003_alter_attendanceuser_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='holiday_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceuser',
            name='overtime_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='last_info',
            field=models.TextField(blank=True, default=' +', max_length=250, null=True),
        ),
    ]
