# Generated by Django 4.2 on 2024-03-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0004_attendanceuser_holiday_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceuser',
            name='month',
        ),
    ]
