# Generated by Django 5.0.1 on 2024-03-02 14:57

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0004_attendanceuser_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='month',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
