# Generated by Django 4.2 on 2024-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0005_remove_attendanceuser_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='month',
            field=models.PositiveSmallIntegerField(default=None, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='attendanceuser',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, editable=False, max_length=4, null=True),
        ),
    ]
