# Generated by Django 5.0.1 on 2024-03-02 15:04

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0005_alter_attendanceuser_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
    ]
