# Generated by Django 4.2 on 2024-03-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0006_attendanceuser_month_attendanceuser_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='month',
            field=models.PositiveSmallIntegerField(default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, max_length=4, null=True),
        ),
    ]
