# Generated by Django 5.0.1 on 2024-03-02 15:13

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0006_alter_attendanceuser_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_created=True, blank=True, null=True),
        ),
    ]
