# Generated by Django 4.2 on 2024-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0007_alter_attendanceuser_month_alter_attendanceuser_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='last_info',
            field=models.TextField(blank=True, default=' +', max_length=450, null=True),
        ),
    ]
