# Generated by Django 4.2 on 2024-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0008_alter_attendanceuser_last_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='last_info',
            field=models.TextField(blank=True, default=' +', max_length=800, null=True),
        ),
    ]
