# Generated by Django 4.2 on 2024-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0009_alter_attendanceuser_last_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='month',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
