# Generated by Django 4.2 on 2025-01-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0010_alter_attendanceuser_month_alter_attendanceuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='absent',
            field=models.BooleanField(default=True),
        ),
    ]
