# Generated by Django 4.2 on 2025-01-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0011_attendanceuser_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceuser',
            name='absent',
        ),
    ]
