# Generated by Django 4.2 on 2025-02-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance_app', '0012_remove_attendanceuser_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_AttendanceUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='month',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
