# Generated by Django 4.2 on 2025-02-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0013_alter_attendanceuser_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceuser',
            name='created_by',
        ),
    ]
