# Generated by Django 4.2 on 2025-02-07 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0014_remove_attendanceuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
