# Generated by Django 4.2 on 2025-02-07 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0015_alter_attendanceuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
