# Generated by Django 4.2 on 2025-02-24 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0016_alter_attendanceuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='overtime_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
