# Generated by Django 4.2 on 2025-03-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0017_attendanceuser_overtime_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='month',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='year',
            field=models.PositiveSmallIntegerField(default=1403, editable=False),
        ),
    ]
