# Generated by Django 4.2 on 2025-03-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0023_delay'),
        ('Attendance_app', '0018_alter_attendanceuser_month_alter_attendanceuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='delay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='pricing.delay'),
        ),
    ]
