# Generated by Django 4.2 on 2025-03-22 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance_app', '0019_attendanceuser_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('absent_users', models.ManyToManyField(related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
