# Generated by Django 4.2 on 2025-03-28 16:49

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0020_absencerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerecord',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
