# Generated by Django 4.2 on 2025-03-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0021_alter_absencerecord_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absencerecord',
            old_name='date',
            new_name='created_date',
        ),
    ]
