# Generated by Django 4.2 on 2025-03-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0022_rename_date_absencerecord_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerecord',
            name='month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='absencerecord',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
