# Generated by Django 4.2 on 2025-03-30 14:01

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0024_absencewarning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencewarning',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
