# Generated by Django 4.2 on 2025-05-16 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance_app', '0025_alter_absencewarning_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('status', models.CharField(choices=[('absent', 'غیبت'), ('delay', 'تاخیر'), ('overtime', 'اضافه\u200cکاری')], max_length=20)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AbsenceRecord',
        ),
        migrations.AddField(
            model_name='absencewarning',
            name='related_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='Attendance_app.attendancestatus'),
        ),
    ]
