# Generated by Django 4.2 on 2025-05-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0026_attendancestatus_delete_absencerecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancestatus',
            name='date',
        ),
    ]
