# Generated by Django 4.2 on 2025-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0027_remove_attendancestatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestatus',
            name='month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendancestatus',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
