# Generated by Django 4.2 on 2025-05-16 18:36

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0028_attendancestatus_month_attendancestatus_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatus',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
