from django.urls import path
from . import views

app_name = 'managing'
urlpatterns = [
# path('update-duration/', views.update_duration_view, name='update_duration'),
    path('setting/', views.setting_app, name='setting_app'),
    path('userlist/<str:pk>/<int:month>/<int:year>/', views.staff_user_list, name='user_list'),
    path('download_excel/<str:pk>/<int:month>/<int:year>/', views.download_excel, name='download_excel'),
    path('no_confirmation_users/', views.no_confirmation_check, name='no_confirmation_check'),
    path('confirm/<str:pk>/', views.accept_confirmation, name='confirm'),
    path('reject/<str:pk>/', views.not_accepted_confirmation, name='reject'),
    path('info_users/<int:month>/<int:year>/', views.in_progress_users, name='info_users'),
    path('none_progress/<int:month>/<int:year>/', views.non_progress, name='non_progress'),
    path('absent_record_list/<int:month>/<int:year>/', views.absent_record_list_view, name='absent_record_list'),
    path('absent_users_list/<str:date>/', views.absent_record_detail_view, name='absent_users_list'),
    path('absences/<int:user_id>/<int:month>/<int:year>/', views.manager_view_absences_for_user, name='manager_user_absence_detail'),
    path('delete_none_progress/<int:pk>/<int:month>/<int:year>/', views.delete_non_progress, name='delete_none_progress'),
    path('delete_monthly_non_progress/<int:month>/<int:year>/', views.delete_monthly_non_progress, name='delete_monthly_non_progress'),
    path('all_vacations/', views.all_vacations, name='all_vacations'),
    path('create_user/', views.create_user_for_staff, name='create_user'),
    path('create_shift/', views.create_shift_work, name='create_shift_work'),
    path('create_position/', views.create_position, name='create_position'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('create_holiday/', views.create_holiday, name='create_holiday'),
    path('user_delete/<str:pk>/<int:mo>/<int:year>/', views.delete_user_for_staff, name='delete_user_for_staff'),
    path('user_update/<str:pk>/', views.update_user_for_staff, name='update_user_for_staff'),
    path('shift_list/', views.list_shift_work, name='list_shift_work'),
    path('shift_delete/<int:pk>/', views.delete_shift_work, name='delete_shift_work'),
    path('shift_update/<int:pk>/', views.update_shift_work, name='update_shift_work'),
    path('position_list/', views.list_position, name='list_position'),
    path('position_delete/<int:pk>/', views.delete_position, name='delete_position'),
    path('position_update/<int:pk>/', views.update_position, name='update_position'),
    path('holiday_delete/<int:pk>/', views.delete_holiday, name='delete_holiday'),
    path('holiday_update/<int:pk>/', views.update_holiday, name='update_holiday'),
    path('profile_list/', views.list_profile, name='list_profile'),
    path('profile_delete/<int:pk>/', views.delete_profile, name='delete_profile'),
    path('profile_update/<int:pk>/', views.update_profile, name='update_profile'),
    path('check_vacations/', views.confirmation_vacation, name='check_vacation_confirmation'),
    path('confirm_vacation/<int:pk>/', views.accepted_vacation, name='accepted_vacation'),
    path('reject_vacation/<int:pk>/', views.not_accepted_vacation, name='not_accepted_vacation'),
]
