# Generated by Django 5.0.1 on 2024-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
