# Generated by Django 4.2 on 2024-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vacation',
            field=models.ManyToManyField(null=True, related_name='vacation_profile', to='pricing.vacation'),
        ),
    ]
