# Generated by Django 5.0.1 on 2024-03-02 14:57

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_income_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_Date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
