# Generated by Django 4.2 on 2024-03-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_profile_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='vacations',
        ),
    ]
