# Generated by Django 5.0.1 on 2024-03-02 15:10

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_income_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
