# Generated by Django 4.2 on 2024-03-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_remove_positions_vacations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shift_works',
        ),
    ]
