# Generated by Django 4.2 on 2024-03-19 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_remove_profile_shift_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='type',
        ),
        migrations.AddField(
            model_name='vacation',
            name='vacation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='pricing.vacationtype'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vacation',
            field=models.ManyToManyField(blank=True, related_name='vacation_profile', to='pricing.vacation'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL),
        ),
    ]
