# Generated by Django 4.2 on 2024-03-20 09:15

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_remove_vacation_type_vacation_vacation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='Surplus',
        ),
        migrations.RemoveField(
            model_name='income',
            name='USer',
        ),
        migrations.RemoveField(
            model_name='income',
            name='User_income',
        ),
        migrations.AlterField(
            model_name='income',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='job_time',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='income',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pricing.profile'),
        ),
        migrations.AddField(
            model_name='income',
            name='surplus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='user_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
