# Generated by Django 4.2 on 2024-03-20 09:28

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_remove_income_surplus_remove_income_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_created=True, blank=True, null=True),
        ),
    ]
