# Generated by Django 5.0.1 on 2024-03-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
