# Generated by Django 4.2 on 2024-03-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_alter_income_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='created_by',
        ),
        migrations.AddField(
            model_name='vacation',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
