# Generated by Django 4.2 on 2024-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_remove_vacation_created_by_vacation_time2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.PositiveSmallIntegerField(max_length=2),
        ),
    ]
