# Generated by Django 4.2 on 2024-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_income_year_alter_income_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
