# Generated by Django 4.2 on 2024-03-31 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_income_month_alter_income_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftwork',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poss', to='pricing.positions'),
        ),
        migrations.CreateModel(
            name='NoneInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ManyToManyField(related_name='nonprogres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
