# Generated by Django 4.2 on 2024-03-31 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_shiftwork_name_alter_profile_profile_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noneinprogress',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='nonprogres', to=settings.AUTH_USER_MODEL),
        ),
    ]
