# Generated by Django 4.2 on 2024-04-01 11:23

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_alter_noneinprogress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noneinprogress',
            name='date',
        ),
        migrations.AddField(
            model_name='noneinprogress',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noneinprogress',
            name='month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noneinprogress',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
