# Generated by Django 4.2 on 2024-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_remove_noneinprogress_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
    ]
