# Generated by Django 4.2 on 2024-04-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_positions_monthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='time',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='time2',
        ),
    ]
