# Generated by Django 4.2 on 2024-04-03 14:04

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_remove_vacation_time_remove_vacation_time2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_created=True),
        ),
    ]
