# Generated by Django 4.2 on 2025-01-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_alter_holidays_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
