# Generated by Django 4.2 on 2025-01-09 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='required_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
