# Generated by Django 4.2 on 2025-01-09 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_positions_required_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='required_time',
        ),
        migrations.AddField(
            model_name='shiftwork',
            name='required_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
