# Generated by Django 4.2 on 2025-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0020_remove_positions_required_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='absent',
            field=models.BooleanField(default=True),
        ),
    ]
