# Generated by Django 4.2 on 2025-02-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_customuser_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='work_days',
        ),
    ]
