# Generated by Django 4.2 on 2025-03-08 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0022_remove_positions_work_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', django_jalali.db.models.jDateField(auto_created=True, blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(null=True)),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('delay_time', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_delays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
