# Generated by Django 4.2 on 2025-03-08 20:02

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0023_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delay',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
    ]
