# Generated by Django 4.2 on 2025-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0024_alter_delay_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
