# Generated by Django 4.2 on 2025-06-02 16:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0025_positions_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=django_jalali.db.models.jDateField(auto_created=True),
        ),
    ]
