# Generated by Django 4.2 on 2025-06-02 17:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_alter_holidays_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
