# Generated by Django 5.0.1 on 2024-02-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About')),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='WhyUs')),
                ('name', models.CharField(max_length=65)),
                ('position', models.CharField(max_length=120)),
                ('facebook', models.CharField(max_length=120)),
                ('instagram', models.CharField(max_length=120)),
                ('x', models.CharField(max_length=120)),
                ('linkedin', models.CharField(max_length=120)),
                ('youtube', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='WhyUs')),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField()),
            ],
        ),
    ]
