# Generated by Django 5.0.1 on 2024-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
