# Generated by Django 5.0.1 on 2024-02-26 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_slider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/slider', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/slider', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
        migrations.AddField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/slider', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
        migrations.AddField(
            model_name='whyus',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/slider', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
    ]
