# Generated by Django 5.0.1 on 2024-03-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
