# Generated by Django 5.0.1 on 2024-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
