# Generated by Django 4.2 on 2025-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_emailcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
