# Generated by Django 4.2 on 2025-03-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_emailcode_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
